import type { RegistryEntry } from "../../shared.ts";
import { resolvePublicCred } from "../../shared.ts";
import { getOmnirushUserAgent } from "../../../providerHeaderProfiles.ts";

export const omnirushProvider: RegistryEntry = {
  id: "omnirush",
  alias: "omr",
  format: "openai-responses",
  executor: "default",
  forceStream: true,
  baseUrl: "https://omnirush.ai/omnirush/v1/responses",
  modelsUrl: "https://omnirush.ai/omnirush/v1/models",
  authType: "oauth",
  authHeader: "bearer",
  defaultContextLength: 400000,
  headers: {
    "User-Agent": getOmnirushUserAgent(),
  },
  oauth: {
    clientIdDefault: resolvePublicCred("omnirush_id"),
    tokenUrl: "https://omnirush.ai/omnirush/device/token",
  },
  models: [
    {
      id: "gpt-6-astra",
      name: "GPT 6 Astra",
      targetFormat: "openai-responses",
      supportsReasoning: true,
      supportedThinkingEfforts: ["low", "high", "xhigh", "max"],
      contextLength: 400000,
      maxOutputTokens: 128000,
      toolCalling: true,
      supportsVision: true,
    },
    {
      id: "gpt-6-sol",
      name: "GPT 6 Sol",
      targetFormat: "openai-responses",
      supportsReasoning: true,
      supportedThinkingEfforts: ["low", "high", "xhigh", "max"],
      contextLength: 400000,
      maxOutputTokens: 128000,
      toolCalling: true,
      supportsVision: true,
    },
    {
      id: "gpt-5.6-sol",
      name: "GPT-5.6 Sol",
      targetFormat: "openai-responses",
      supportsReasoning: true,
      supportedThinkingEfforts: ["low", "high", "xhigh", "max"],
      contextLength: 400000,
      maxOutputTokens: 128000,
      toolCalling: true,
      supportsVision: true,
    },
    {
      id: "meta-muse-spark",
      name: "Meta Muse Spark",
      targetFormat: "openai-responses",
      supportsReasoning: true,
      contextLength: 400000,
      maxOutputTokens: 128000,
      toolCalling: true,
      supportsVision: true,
    },
    {
      id: "muse-spark-1.1",
      name: "Muse Spark 1.1",
      targetFormat: "openai-responses",
      supportsReasoning: true,
      contextLength: 400000,
      maxOutputTokens: 128000,
      toolCalling: true,
      supportsVision: true,
    },
  ],
  passthroughModels: true,
};
